# Generated by Django 2.2.5 on 2021-01-26 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_envio', models.DateField(blank=True, null=True)),
                ('area', models.TextField()),
                ('resumo', models.TextField()),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cadastros.Pessoa')),
            ],
            options={
                'verbose_name_plural': 'Autores',
            },
            bases=('cadastros.pessoa',),
        ),
        migrations.CreateModel(
            name='Avaliador',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cadastros.Pessoa')),
                ('numero_registro', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Avaliadores',
            },
            bases=('cadastros.pessoa',),
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('ddd', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=200)),
                ('pessoa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='cadastros.Pessoa')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('ano', models.IntegerField()),
                ('projeto', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premios', to='cadastros.Projeto')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('premio', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cronograma', to='cadastros.Premio')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='projeto',
            name='autor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='cadastros.Autor'),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parecer', models.TextField(blank=True, null=True)),
                ('nota', models.FloatField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('projeto', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_projeto', to='cadastros.Projeto')),
                ('avaliador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_avaliador', to='cadastros.Avaliador')),
            ],
            options={
                'verbose_name_plural': 'Avaliações',
            },
        ),
    ]
