# Generated by Django 2.2.5 on 2021-01-27 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='avaliador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='cadastros.Avaliador'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='projeto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='cadastros.Projeto'),
        ),
    ]
